### ISSUE TITLE
frontend app not working

### ISSUE THREAD

**Issue by freemjstudio** [CambioML/pykoi#42]
Hi, I like your repo and I'd like to contribute & test pykoi.

I've installed pykoi, conda, and git repo and I've got some problems with running frontend app 
I assume it's the matter of the Node.js version and I'd like to know which version is compatible with frontend Node
 
Thank you 
![image](https://github.com/CambioML/pykoi/assets/41604678/2de87e51-d3fd-4e19-9c82-2b2f05f18799)

**Comment by jwilber** [comment]
Ty! Did you run `npm install` first?

e.g.

```
git clone https://github.com/CambioML/pykoi.git
cd pykoi/pykoi/frontend
npm run install
npm run build
 ```

**Comment by freemjstudio** [comment]
yes I tried it ! 

and My environment is ec2 Ubuntu 20.04

**Comment by goldmermaid** [comment]
I tested on node v18.16.1 with below command

```
cd pykoi/pykoi/frontend
npm install
npm run build
```

Can you try it again and let us know whether it works for u?

**Comment by goldmermaid** [comment]
Close the ticket.

**Comment by goldmermaid** [comment]
issue should be resolved now.
